import { ModelType, VisualizationType } from '../types/geometry';

export interface RegistryItem {
  type: ModelType;
  titleVi: string;
  engine: string;
  domain: 'geometry2d' | 'geometry3d' | 'algebra' | 'probability' | 'statistics';
  dimension: '2D' | '3D' | 'N/A';
  objects: string[];
  measurements: string[];
  requiredCases: string[];
  defaultParams: Record<string, number>;
  visualizationType: VisualizationType;
}

export const EXPERIMENT_REGISTRY: Record<ModelType, RegistryItem> = {
  two_circles: {
    type: 'two_circles',
    titleVi: 'Vị trí tương đối của hai đường tròn',
    engine: 'RelativePositionTwoCirclesEngine',
    domain: 'geometry2d',
    dimension: '2D',
    objects: ['circle', 'circle'],
    measurements: ['R', 'r', 'OO_prime (d)'],
    requiredCases: [
      'external_disjoint (d > R+r)',
      'external_tangent (d = R+r)',
      'intersect_two_points (|R-r| < d < R+r)',
      'internal_tangent (d = |R-r|)',
      'internal_disjoint (d < |R-r|)',
      'concentric (d = 0)',
    ],
    defaultParams: { r1: 5, r2: 3, d: 6 },
    visualizationType: 'geometry2d',
  },
  line_circle: {
    type: 'line_circle',
    titleVi: 'Vị trí tương đối của đường thẳng và đường tròn',
    engine: 'RelativePositionLineCircleEngine',
    domain: 'geometry2d',
    dimension: '2D',
    objects: ['line', 'circle'],
    measurements: ['R', 'h (d(O, d))'],
    requiredCases: [
      'disjoint (h > R)',
      'tangent (h = R)',
      'intersect (h < R)',
    ],
    defaultParams: { r: 5, h: 4, angle: 0 },
    visualizationType: 'geometry2d',
  },
  cylinder: {
    type: 'cylinder',
    titleVi: 'Hình trụ (Cylinder)',
    engine: 'Cylinder3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['cylinder'],
    measurements: ['r (Bán kính)', 'h (Chiều cao)', 'S_xq', 'V'],
    requiredCases: ['Thay đổi bán kính r', 'Thay đổi chiều cao h', 'Khai triển mặt xung quanh'],
    defaultParams: { radius: 3, height: 6 },
    visualizationType: '3d',
  },
  cone: {
    type: 'cone',
    titleVi: 'Hình nón (Cone)',
    engine: 'Cone3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['cone'],
    measurements: ['r (Bán kính)', 'h (Chiều cao)', 'l (Đường sinh)', 'S_xq', 'V'],
    requiredCases: ['Thay đổi bán kính r', 'Thay đổi chiều cao h', 'Khai triển thành quạt tròn'],
    defaultParams: { radius: 3, height: 6 },
    visualizationType: '3d',
  },
  sphere: {
    type: 'sphere',
    titleVi: 'Hình cầu (Sphere)',
    engine: 'Sphere3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['sphere'],
    measurements: ['R (Bán kính)', 'S (Mặt cầu)', 'V (Thể tích)'],
    requiredCases: ['Thay đổi bán kính R', 'Mặt cắt qua tâm'],
    defaultParams: { radius: 4 },
    visualizationType: '3d',
  },
  cuboid: {
    type: 'cuboid',
    titleVi: 'Hình hộp chữ nhật (Cuboid)',
    engine: 'Cuboid3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['cuboid'],
    measurements: ['a (Dài)', 'b (Rộng)', 'c (Cao)', 'S_xq', 'V'],
    requiredCases: ['Thay đổi kích thước 3 chiều', 'Khai triển 6 mặt'],
    defaultParams: { a: 5, b: 4, h: 3 },
    visualizationType: '3d',
  },
  cube: {
    type: 'cube',
    titleVi: 'Hình lập phương (Cube)',
    engine: 'Cube3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['cube'],
    measurements: ['a (Cạnh)', 'S_tp', 'V'],
    requiredCases: ['Thay đổi độ dài cạnh a'],
    defaultParams: { a: 4 },
    visualizationType: '3d',
  },
  parabol: {
    type: 'parabol',
    titleVi: 'Hình Paraboloid 3D',
    engine: 'Parabol3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['paraboloid'],
    measurements: ['a (Độ mở)', 'h (Chiều cao)'],
    requiredCases: ['Xoay mặt paraboloid'],
    defaultParams: { a: 0.5, h: 5 },
    visualizationType: '3d',
  },
  graph_linear: {
    type: 'graph_linear',
    titleVi: 'Đồ thị Hàm số bậc nhất y = ax + b',
    engine: 'LinearFunctionEngine',
    domain: 'algebra',
    dimension: '2D',
    objects: ['line', 'coordinate_system'],
    measurements: ['Hệ số góc a', 'Tung độ gốc b'],
    requiredCases: ['a > 0 (Đồng biến)', 'a < 0 (Nghịch biến)', 'Hai đường thẳng song song/cắt nhau'],
    defaultParams: { a: 1, b: 2 },
    visualizationType: 'graph',
  },
  graph_parabola: {
    type: 'graph_parabola',
    titleVi: 'Đồ thị Parabol y = ax²',
    engine: 'QuadraticFunctionEngine',
    domain: 'algebra',
    dimension: '2D',
    objects: ['parabola', 'coordinate_system'],
    measurements: ['Hệ số a', 'Đỉnh O(0,0)'],
    requiredCases: ['a > 0 (Bề lõm quay lên)', 'a < 0 (Bề lõm quay xuống)', 'Giao điểm với đường thẳng y = mx + n'],
    defaultParams: { a: 0.5, b: 0, h: 0 },
    visualizationType: 'graph',
  },
  probability_sim: {
    type: 'probability_sim',
    titleVi: 'Mô phỏng Xác suất Thực nghiệm',
    engine: 'ProbabilityExperimentEngine',
    domain: 'probability',
    dimension: 'N/A',
    objects: ['coin', 'dice'],
    measurements: ['Số lần thử N', 'Tần số xuất hiện', 'Xác suất thực nghiệm'],
    requiredCases: ['Tung 1 đồng xu', 'Tung 2 xúc xắc', 'Rút thẻ/Rút bóng'],
    defaultParams: { trials: 100 },
    visualizationType: 'probability',
  },
  statistics_sim: {
    type: 'statistics_sim',
    titleVi: 'Mô phỏng Thống kê & Phân tích Dữ liệu',
    engine: 'StatisticsExperimentEngine',
    domain: 'statistics',
    dimension: 'N/A',
    objects: ['data_points'],
    measurements: ['Trung bình (Mean)', 'Trung vị (Median)', 'Tứ phân vị', 'Ngoại lệ (Outliers)'],
    requiredCases: ['Dữ liệu không có ngoại lệ', 'Thêm ngoại lệ cực đoan'],
    defaultParams: { trials: 20 },
    visualizationType: 'statistics',
  },
  prism: {
    type: 'prism',
    titleVi: 'Hình lăng trụ đứng tam giác',
    engine: 'Prism3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['prism'],
    measurements: ['Đáy', 'Chiều cao h', 'Thể tích V'],
    requiredCases: ['Thay đổi chiều cao h'],
    defaultParams: { radius: 3, height: 5 },
    visualizationType: '3d',
  },
  prism_quad: {
    type: 'prism_quad',
    titleVi: 'Hình lăng trụ đứng tứ giác (đáy hình thang)',
    engine: 'PrismQuad3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['prism_quad'],
    measurements: ['Đáy lớn a, đáy nhỏ b', 'Chiều cao đáy d', 'Chiều cao h', 'Thể tích V'],
    requiredCases: ['Thay đổi chiều cao h'],
    defaultParams: { a: 6, b: 3, d: 4, height: 5 },
    visualizationType: '3d',
  },
  pyramid_triangular: {
    type: 'pyramid_triangular',
    titleVi: 'Hình chóp tam giác đều',
    engine: 'PyramidTriangular3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['pyramid_triangular'],
    measurements: ['Cạnh đáy a', 'Chiều cao h', 'Thể tích V'],
    requiredCases: ['Thay đổi chiều cao h'],
    defaultParams: { a: 4, height: 5 },
    visualizationType: '3d',
  },
  pyramid: {
    type: 'pyramid',
    titleVi: 'Hình chóp tứ giác đều',
    engine: 'Pyramid3DEngine',
    domain: 'geometry3d',
    dimension: '3D',
    objects: ['pyramid'],
    measurements: ['Đáy', 'Chiều cao h', 'Thể tích V'],
    requiredCases: ['Thay đổi chiều cao h'],
    defaultParams: { radius: 3, height: 5 },
    visualizationType: '3d',
  },
  algebra_identity: {
    type: 'algebra_identity',
    titleVi: 'Nhân đơn thức với đa thức a(b+c) & Hằng đẳng thức Đại số',
    engine: 'AlgebraIdentityEngine',
    domain: 'algebra',
    dimension: '2D',
    objects: ['square', 'rectangle', 'area_dissection'],
    measurements: ['Đơn thức a', 'Hạng tử b', 'Hạng tử c', 'S1 = ab', 'S2 = ac', 'S_tong = a(b+c)'],
    requiredCases: ['Khảo sát a(b+c) = ab + ac', 'Khảo sát (a+b)²', 'Khảo sát (a+b)(c+d)'],
    defaultParams: { a: 4, b: 5, c: 8, d: 0 },
    visualizationType: 'geometry2d',
  },
  pythagorean_theorem: {
    type: 'pythagorean_theorem',
    titleVi: 'Khám phá & Xây dựng Định lý Pythagore',
    engine: 'PythagoreanTheoremEngine',
    domain: 'geometry2d',
    dimension: '2D',
    objects: ['right_triangle', 'square_a', 'square_b', 'square_c'],
    measurements: ['Cạnh a', 'Cạnh b', 'Cạnh huyền c', 'S1 = a²', 'S2 = b²', 'S3 = c²', 'S1 + S2'],
    requiredCases: ['Tam giác 3-4-5', 'Tam giác 6-8-10', 'Tam giác vuông cân', 'Ghép diện tích'],
    defaultParams: { a: 3, b: 4 },
    visualizationType: 'geometry2d',
  },
  congruent_triangles: {
    type: 'congruent_triangles',
    titleVi: 'Hai tam giác bằng nhau (Congruent Triangles)',
    engine: 'CongruentTrianglesEngine',
    domain: 'geometry2d',
    dimension: '2D',
    objects: ['triangle_abc', 'triangle_a_prime_b_prime_c_prime'],
    measurements: ['AB, BC, CA', 'A\'B\', B\'C\', C\'A\'', '∠A, ∠B, ∠C', '∠A\', ∠B\', ∠C\'', 'Diện tích S'],
    requiredCases: ['Trường hợp C-C-C', 'Trường hợp C-G-C', 'Trường hợp G-C-G', 'Phản ví dụ G-G-G', 'Phản ví dụ SSA', 'Chồng khít'],
    defaultParams: { a: 5, b: 6, c: 7 },
    visualizationType: 'geometry2d',
  },
  similar_triangles: {
    type: 'similar_triangles',
    titleVi: 'Tam giác đồng dạng và Hình đồng dạng (Similar Shapes)',
    engine: 'SimilarTrianglesEngine',
    domain: 'geometry2d',
    dimension: '2D',
    objects: ['triangle_abc', 'triangle_a_prime_b_prime_c_prime', 'squares', 'rectangles', 'circles'],
    measurements: ['AB, BC, CA', 'A\'B\', B\'C\', C\'A\'', 'Tỉ số k', '∠A, ∠B, ∠C', '∠A\', ∠B\', ∠C\'', 'Diện tích S, S\'', 'Tỉ số diện tích k²'],
    requiredCases: ['Tỉ số k', 'Trường hợp G-G', 'Trường hợp C-C-C', 'Trường hợp C-G-C', 'Phản ví dụ', 'Hình vuông', 'Hình chữ nhật', 'Hình tròn', 'Co về k=1 và Chồng khít'],
    defaultParams: { k: 1.5, a: 6, b: 7, c: 8 },
    visualizationType: 'geometry2d',
  },
};
